# For more info on HTTP files go to https://aka.ms/vs/httpfile

#Colores no disponibles: Negro, Beige, Verde, Anaranjado
@host = localhost:7252

GET https://{{host}}/api/cortinas/

###

GET https://{{host}}/api/cortinas/all

###

GET https://{{host}}/api/cortinas/roller

###

GET https://{{host}}/api/cortinas/bandasverticales/all

###

GET https://{{host}}/api/cortinas/debarral/all

###

GET https://{{host}}/api/cortinas/debarral

###

GET https://{{host}}/api/color/

###

GET https://{{host}}/api/color/cortinas/roller/all

###

GET https://{{host}}/api/color/cortinas/debarral

###

GET https://{{host}}/api/color/telas/screen

###

GET https://{{host}}/api/color/telas/algodon/all

###

GET https://{{host}}/api/color/telas/blanco

###

GET https://{{host}}/api/color/telas/negro

###

GET https://{{host}}/api/tela/blackout

###

GET https://{{host}}/api/tela/blackout

###

GET https://{{host}}/api/tela/

###

GET https://{{host}}/api/tela/all